apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: prom-{{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  endpoints:
  - port: prom-http
    interval: 300s
