apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://grafana.github.io/helm-charts'
    chart: grafana
    targetRevision: "${GRAFANA_HELM_VERSION}"
    helm:
      valueFiles:
      - $values/grafana-config/grafana-values/values.yaml
      valuesObject:
        grafana.ini:
          auth:
            oauth_allow_insecure_email_lookup: true
          paths:
            plugins: /var/lib/grafana/plugins/
      parameters:
#      - name: "ingress.hosts[0]"
#        value: "grafan.mydomain.com"
  - repoURL: ${BB_URL}
    targetRevision: ${ENV}
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    # preserveResourcesOnDeletion: true   
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - Replace=true                   
