apiVersion: v1
kind: Secret
metadata:
  name: contact-application
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: ${URL} 
  password: ${TOKEN}
  username: x-token-auth
