apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ["/bin/sh", "-ec", "sleep 7200"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
