apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-
  namespace: argo
spec:
  entrypoint: diamond
  templates:
  - name: diamond 
    dag:
      tasks:
      - name: A
        templateRef:
          name: whalesay-template
          template: whalesay
        arguments:
          parameters:
          - name: message
            value: "A"
      - name: B
        templateRef:
          name: whalesay-template
          template: whalesay 
        arguments:
          parameters:
          - name: message
            value: "B"
      - name: C
        dependencies: [A]
        templateRef:
          name: whalesay-template
          template: whalesay
        arguments:
          parameters:
          - name: message
            value: "C"
      - name: D
        dependencies: [B, C]
        templateRef:
          name: whalesay-template
          template: whalesay
        arguments:
          parameters:
          - name: message
            value: "D"
