name: gcp-potential-disco

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
  pull_request:
    # paths: # setup paths if necessary
    branches:
      - main
    types:
      - opened # default
      - synchronize # default
      - reopened # default
      - closed

env:
  WORKING_DIR:  ${{ vars.WORKING_DIR }}

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: "PRD"
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093

      with:
        create_credentials_file: 'true'
        workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

    - uses: opentofu/setup-opentofu@fc711fa910b93cba0f3fbecaafc9f42fd0c411cb

    - name: OpenTofu Init
      id: init
      run: tofu init
      env: 
         TF_VAR_project: ${{ vars.TFVAR_GCP_PROJECT }}

    - name: OpenTofu Validate
      id: validate
      run: tofu validate -no-color
      env: 
         TF_VAR_project: ${{ vars.TFVAR_GCP_PROJECT }}

    - uses: google-github-actions/get-gke-credentials@3da1e46a907576cefaa90c484278bb5b259dd395
      if: always()
      continue-on-error: true
      with:
        cluster_name: "${{ vars.TFVAR_GCP_PROJECT }}-gke"
        location: ${{ vars.REGION }}
        project_id: ${{ vars.TFVAR_GCP_PROJECT }}

    - name: OpenTofu Plan
      id: plan
      run: tofu plan -no-color
      continue-on-error: true
      env: 
         TF_VAR_project: ${{ vars.TFVAR_GCP_PROJECT }}

    - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3
      if: github.event_name == 'pull_request'
      env:
        PLAN: "tofu\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.REPO_PAT_TOKEN }}
        script: |
          const output = `#### OpenTofu Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### OpenTofu Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### OpenTofu Validation 🤖\`${{ steps.validate.outcome }}\`
          <details><summary>Validation Output</summary>
     
          \`\`\`\n
          ${{ steps.validate.outputs.stdout }}
          \`\`\`

          </details>

          #### OpenTofu Plan 📖\`${{ steps.plan.outcome }}\`
      
          <details><summary>Show Plan</summary>

          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`

          </details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.WORKING_DIR }}\`, Workflow: \`${{ github.workflow }}\`*`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

    - name: OpenTofu Apply
      id: apply
      #if: github.event.pull_request.merged == true
      run: tofu apply -auto-approve -input=false
      env: 
         TF_VAR_project: ${{ vars.TFVAR_GCP_PROJECT }}

    - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3
      if: github.event.pull_request.merged == true
      with:
        script: |
          const output = `#### OpenTofu Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### OpenTofu Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### OpenTofu Validation 🤖\`${{ steps.validate.outcome }}\`
          #### OpenTofu Apply 📖\`${{ steps.apply.outcome }}\`
          <details><summary>Show Apply</summary>
          \`\`\`\n
          ${{ steps.apply.outputs.stdout }}
          \`\`\`
          </details>
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.WORKING_DIR }}\`, Workflow: \`${{ github.workflow }}\`*`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
