apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${NAME}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ${GH_URL}
    targetRevision: ${ENV}
    path: ${PATH}
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - values.yaml
      valuesObject:
        labels:
          upgrade_stage: "placeholder"
  destination:
    server: https://kubernetes.default.svc
    namespace: "${NAMESPACE}"
  syncPolicy:
    # preserveResourcesOnDeletion: true   
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - Replace=true                   
